#!/bin/bash

export RIVPROJECT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export RIVET_ANALYSIS_PATH=$RIVET_ANALYSIS_PATH:$RIVPROJECT; export RIVET_REF_PATH=$RIVET_REF_PATH:$RIVPROJECT; export RIVET_DATA_PATH=$RIVET_DATA_PATH:$RIVPROJECT; export RIVET_INFO_PATH=$RIVET_INFO_PATH:$RIVPROJECT
